### ISSUE TITLE
Additional references

### ISSUE THREAD

**Issue by mdozmorov** [pollardlab/contact_map_scoring#1]
Great work, enjoyed reading it. Not an issue, just a suggestion to consider a similar work, HiC1Dmetrics, https://github.com/wangjk321/HiC1Dmetrics, https://doi.org/10.1093/bib/bbab509, which also provides recommendations for comparing Hi-C maps.

**Comment by lgunsalus** [comment]
Thanks so much! We'll definitely cite it!
